version: '3.8'

networks:
  default:

services:
  database:
    image: postgres:14-alpine
    container_name: inspireyou22
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "./.data/db:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inspireyou2